# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-24 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='viewHotEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smallImg', models.ImageField(upload_to='')),
                ('nameEvent', models.CharField(max_length=200)),
            ],
        ),
    ]
