# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-24 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewhotevent',
            name='smallImg',
            field=models.ImageField(upload_to='dawnloadImg'),
        ),
    ]
